runners:
  - name: gpu-runner
    cloud: aws
    instance_type: g4dn.xlarge
    # AMI options: Ubuntu with Nvidia drivers
    # ami-0c6b386534e3e1534
    # AMI options: DLAMI Ubuntu 22.04
    # ami-014cf2391cb36896e
    machine_image: ami-014cf2391cb36896e
    region: us-east-2
    preemptible: true
    labels:
      - cirun-aws-gpu
